# Moving from Python2 to Python3

Python 2 has a limited lifetime, and by 2020, there will no longer be any active development on Python 2.

http://legacy.python.org/dev/peps/pep-0373/

Why?  Apparently it was easier to make a shiny new python by breaking backwards compatibility.  The good news is it's relatively painless to switch small projects over to Python 3, and most major Python packages already support Python 3 (including most of the scientific stack: numpy, scipy, pandas, astropy).

In [14]:
import sys
print(sys.version)

3.5.3 (default, Mar 21 2017, 17:21:33) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]


## A (non-exhaustive) list of differences between Python 2 and Python 3

* `print` is now a function, no longer a keyword
* `exec` is now a function, no longer a keyword
* division, `/`, no longer truncates! (no more 2/3 == 0)
* all strings are unicode (this is... controversial)
* the functions `range()`, `zip()`, `map()`, `filter()`, `dict.keys()`, `dict.items()`, `dict.values()`, all return an iterator instead of a list
* exceptions are handled using a slightly different syntax
* strict comparisons, so `'a' < 1` will fail with an error
* from the standard library, `urllib` is reorganized

For a more complete list, see 

http://ptgmedia.pearsoncmg.com/imprint_downloads/informit/promotions/python/python2python3.pdf


## Cool things in Python 3

Some of these have been back-ported to Python 2.7

In [4]:
# python2 has list comprehensions
[x ** 2 for x in range(5)]

[0, 1, 4, 9, 16]

In [5]:
# python3 has dict comprehensions!
{str(x): x ** 2 for x in range(5)}

{'0': 0, '1': 1, '2': 4, '3': 9, '4': 16}

In [6]:
# and set comprehensions
{x ** 2 for x in range(5)}

{0, 1, 4, 9, 16}

In [34]:
# magic dictionary concatenation
some_kwargs = {'do': 'this', 
               'not': 'that'}
other_kwargs = {'use': 'something', 
                'when': 'sometime'}
{**some_kwargs, **other_kwargs}

{'do': 'this', 'not': 'that', 'use': 'something', 'when': 'sometime'}

In [16]:
# unpacking magic
a, *stuff, b = range(5)
print(a)
print(stuff)
print(b)

0
[1, 2, 3]
4


In [23]:
# unicode variable names!
import numpy as np
π = np.pi
np.cos(2 * π)

1.0

In [32]:
# infix matrix multiplication
A = np.random.choice(list(range(-9, 10)), size=(3, 3))
B = np.random.choice(list(range(-9, 10)), size=(3, 3))
print("A = \n", A)
print("B = \n", B)

print("A B = \n", A @ B)
print("A B = \n", np.dot(A, B))

A = 
 [[ 9 -9  8]
 [ 4  2 -9]
 [-4  0  8]]
B = 
 [[ 1  9  6]
 [ 4  7  8]
 [-3  5  5]]
A B = 
 [[-51  58  22]
 [ 39   5  -5]
 [-28   4  16]]
A B = 
 [[-51  58  22]
 [ 39   5  -5]
 [-28   4  16]]


## New string formatting

The old string formatting (with `%`) is depricated in favor of `str.format()`.  A good comparison of the two can be found here: 

https://pyformat.info/

## Unicode
Dealing with unicode can be a pain when \*nix doesn't give or expect unicode.  Sometimes importing data in python3 will give you strings with a weird `b` in front.  These are bytestrings, and they can usually be converted to unicode strings with `bytestring.decode('utf-8')`.

In [41]:
s = 'asdf'
b = s.encode('utf-8')
b

b'asdf'

In [42]:
b.decode('utf-8')

'asdf'

In [43]:
# this will be problematic if other encodings are used...
s = 'asdf'
b = s.encode('utf-32')
b

b'\xff\xfe\x00\x00a\x00\x00\x00s\x00\x00\x00d\x00\x00\x00f\x00\x00\x00'

In [44]:
b.decode('utf-8')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte